name: Deploy to Pantheon
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        git remote add origin ssh://codeserver.dev.941d2f97-5700-459a-bb11-89868d8cc1c6@codeserver.dev.941d2f97-5700-459a-bb11-89868d8cc1c6.drush.in:2222/~/repository.git v-d9
        
